src/Entity/Flat.php
<?php

namespace App\Entity;

use App\Repository\FlatRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;


/**
 * @ORM\Entity(repositoryClass=FlatRepository::class)
 */
class Flat
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank()
     * @Assert\Regex("/^([0-9 ]{1,2}|[a-zA-Z ])*[a-zA-Z]$/", message="Erreur dans le format de l'adresse")
     */
    private ?string $Address;

    /**
     * @ORM\Column(type="integer")
     * @Assert\NotBlank()
     * @Assert\Regex("/^[1-9]{1,2}$/", message="L'appartement doit appartenir a un etage entre 1-99")
     */
    private ?int $Floor;

    /**
     * @ORM\Column(type="integer")
     * @Assert\NotBlank()
     * @Assert\Regex("/^[1-9]{1}$/", message="L'appartement doit contenir un numero de chambres entre 1-9")
     */
    private ?int $Room_number;

    /**
     * @ORM\Column(type="boolean")
     */
    private ?bool $Elevator;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getAddress(): ?string
    {
        return $this->Address;
    }

    public function setAddress(string $Address): self
    {
        $this->Address = $Address;

        return $this;
    }

    public function getFloor(): ?int
    {
        return $this->Floor;
    }

    public function setFloor(int $Floor): self
    {
        $this->Floor = $Floor;

        return $this;
    }

    public function getRoomNumber(): ?int
    {
        return $this->Room_number;
    }

    public function setRoomNumber(int $Room_number): self
    {
        $this->Room_number = $Room_number;

        return $this;
    }

    public function getElevator(): ?bool
    {
        return $this->Elevator;
    }

    public function setElevator(bool $Elevator): self
    {
        $this->Elevator = $Elevator;

        return $this;
    }
}

src/Form/FlatInfoType.php
<?php

namespace App\Form;

use App\Entity\Flat;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class FlatInfoType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('Address', TextType::class, [
                'attr' => [
                    'class' => 'form-control'
                ],
            ])
            ->add('Floor', IntegerType::class,  [
                'attr' => [
                    'class' => 'form-control'
                 ],
            ])
            ->add('Room_number', IntegerType::class,  [
                'attr' => [
                    'class' => 'form-control'
                ],
            ])
            ->add('Elevator', CheckboxType::class,  [
                'required' => false,
                'attr' => [
                    'class' => 'form-check-input'
                ],
            ]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Flat::class,
        ]);
    }
}

src/Controller/FlatsController.php
<?php

namespace App\Controller;

use App\Entity\Flat;
use App\Form\FlatInfoType;
use App\Service\FlatEntityManagerService;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\Config\Definition\Exception\Exception;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class FlatsController extends AbstractController
{
    /**
     * @Route("/", name="flats")
     */
    public function index(EntityManagerInterface $em): Response
    {
        $flatsList = $em->getRepository(flat::class)->findAll();

        return $this->render('flats/index.html.twig', [
            'controller_name' => 'Liste d\'Appartements',
            'flats_list' => $flatsList,
        ]);
    }

    /**
     * @Route("/updateInfo/{id}", name="updateInfo", requirements={"id"="\d+"})
     * @param Request $request
     * @param FlatEntityManagerService $flatEntityManager
     * @return Response
     */
    public function updateFlatInfo(Request $request, FlatEntityManagerService $flatEntityManager): Response
    {
        // Recuperation de l'appartement en BDD
        $flat = $flatEntityManager->getFlatById($request->get('id'));

        // Creation du Form
        $form = $this->createForm(FlatInfoType::class, $flat);

        $form->handleRequest($request);

        // Si le Form est Posté
        if ($form->isSubmitted() && $form->isValid()) {
            $formData = $form->getData();
            // Appel au service qui MAJ les données en BDD
            try {
                $flatEntityManager->updateTable($formData);
                $this->addFlash('success', 'Mise a Jour completé');

                return $this->redirectToRoute('flats', [], 301);
            } catch (Exception $exception) {
                $this->addFlash('error', $exception->getMessage());
            }
        }

        return $this->render('flats/updateForm.html.twig', [
            'update_form' => $form->createView(),
        ]);
    }
}

templates/base.html.twig
<!DOCTYPE html>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        {# Run `composer require symfony/webpack-encore-bundle`
           and uncomment the following Encore helpers to start using Symfony UX #}
        {% block stylesheets %}
            {#{{ encore_entry_link_tags('app') }}#}
        {% endblock %}

        {% block javascripts %}
            {#{{ encore_entry_script_tags('app') }}#}
        {% endblock %}
    </head>
    <body>
        {% block body %}{% endblock %}
    </body>
</html>

templates/flats/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Test Technique Santiago{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1><u>{{ controller_name }}!</u></h1>
    {% for message in app.flashes('success') %}
        <div class="alert alert-success">
            {{ message }}
        </div>
    {% endfor %}
    <div class="flatList_Block">
        {% for flat in flats_list %}
        <div class="flat_block_title">
            <b>Appartement avec ID:{{ flat.id }}</b>
        </div>
        <ul>
            <li>Adresse: {{ flat.Address }}</li>
            <li>Numero de l'etage: {{ flat.floor }}</li>
            <li>Numero de chambres: {{ flat.roomNumber }}</li>
            <li>Ascenseur Inclus: {{ flat.elevator  ? 'Oui' : 'Non' }}</li>
        </ul>
        <a href="/updateInfo/{{ flat.id }}">Modifier l'information</a>
            <p></p>
        {% endfor %}
    </div>
</div>
{% endblock %}

templates/flats/updateForm.html.twig
{% extends 'base.html.twig' %}

{% block title %}Test Technique Santiago{% endblock %}

{% block body %}
    <style>
        .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
        .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
    </style>
<div class="example-wrapper">
{% for message in app.flashes('error') %}
    <div class="alert alert-danger">
        {{ message }}
    </div>
{% endfor %}
    {{ form_start(update_form) }}
    <div class="form-group">
        <label for="InputAdresse">Nouvelle Adresse</label>
        <div class="alert-danger">
            {{ form_errors(update_form.Address) }}
        </div>
        {{ form_widget(update_form.Address) }}
    </div>
    <div class="form-group">
        <label for="InputFloor">Nombre d'etages</label>
        <div class="alert-danger">
            {{ form_errors(update_form.Floor) }}
        </div>
      {{ form_widget(update_form.Floor) }}
    </div>
    <div class="form-group">
        <label for="InputFloor">Nombre de chambres</label>
        <div class="alert-danger">
            {{ form_errors(update_form.Room_number) }}
        </div>
        {{ form_widget(update_form.Room_number) }}
    </div>
    <div class="form-group form-check">
        {{ form_widget(update_form.Elevator) }}
        <label class="form-check-label" for="exampleCheck1">Avec ascenseur?</label>
    </div>
    <button class="btn btn-primary" type="submit"> Mettre a jour </button>
    {{ form_end(update_form) }}
</div>
{% endblock %}